;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        kill-sexp
        paredit-backward
        paredit-forward-kill-word
        ))

(setq mc/cmds-to-run-once
      '(
        ))
